### ISSUE TITLE
dkim signing inhibited by milter_mail_macros in postfix

### ISSUE THREAD

**Issue by pclerie** [rspamd/rspamd.com#341]
For what it's worth, I've been banging my head for a couple days trying to get rspamd to sign outgoing email. I'll spare you the details but I eventually found the answer here: 

https://groups.google.com/d/msg/rspamd/H21EzSabVE8/Ukf4t_ZHAwAJ

And in fact, removing the setting milter_mail_macros from /etc/postfix/main.cf solved the problem nicely. I haven't yet looked at why, but I'm putting this up as an issue because all the tutorials I've looked at include that line. It looks very much like it's no longer needed.

So if rspamd.log has lines containing stuff like:

- dkim_signing; lua_dkim_tools.lua:43: ignoring unauthenticated mail
- DMARC_POLICY_SOFTFAIL(0.10){<yourdomainname> : No valid SPF, No valid DKIM;none;}

try removing milter_mail_macros before pulling hair.

Hope that helps.

**Comment by moisseev** [comment]
@pclerie What is your suggestion? We cannot update third-party tutorials.

**Comment by pclerie** [comment]
Honestly, I don't know. The net is full of tutorials that used to work as is but are now at best misleading and at worst inaccurate. I posted this in the hope that it would be useful for the next persons facing that problem. :-) I realize there isn't much you can do.

Then I find that I was guilty of the thing I'm complaining about: I have no idea how postscript got in there instead of postfix. (Fixed).
