### ISSUE TITLE
wrong (old?) syntax for rspamadm statconvert in FAQ

### ISSUE THREAD

**Issue by fezie** [rspamd/rspamd.com#363]
Hello,

the FAQ says under point "Which backend should I use for statistics"

```
# rspamadm statconvert -d bayes.spam.sqlite -h 127.0.0.1:6379 -s BAYES_SPAM
# rspamadm statconvert -d bayes.ham.sqlite -h 127.0.0.1:6379 -s BAYES_HAM \
-c learn_cache.sqlite
```

But these commands don't seem to be valid anymore for 1.8. Actually I have the current 1.8.1 experimental snapshot installed:

```
# r# rspamadm statconvert -d bayes.spam.sqlite -h 127.0.0.1:6379 -s BAYES_SPAM
No spam-db specified
```

It seems that you must specify --spam-db and --ham-db now at once. Not in 2 seperate commands

**Comment by ophian** [comment]
I have the `No spam-db specified` returncode too and don't really know what to do.
Could someone please add a recent rspamd-2.1 **working** example to convert previous sqlite dbs to redis?
Thank you.
