### ISSUE TITLE
Something wrong with the composite weight rules

### ISSUE THREAD

**Issue by resec** [rspamd/rspamd.com#385]
Hi, I found some typos in here https://github.com/rspamd/rspamd.com/blob/master/doc/configuration/composites.md#composite-weight-rules.

If I am guessing right, the `~` should be meaning to keep the symbol while remove the weight? So it should be 

> * If `C` is `~A & B`, then rule `A` is preserved, but it's weight is removed,
  leading to the total weight of `W_c` only

instead of 

> * If `C` is `~A & B`, then rule `A` is preserved, but it's weight is removed,
  leading to the total weight of `W_a` only

Then in few lines below:

> If we rewrite the previous example but replace `-` with `~` then `DATE_IN_PAST` will be removed (however, its weight won't be removed):

This does not making sense.

By the way, the second example is no difference with the first example.

Any ideas? But actually what is the meaning of `~`? Clarify it, then others are just correcting typos in the doc.

**Comment by resec** [comment]
Checking form the code, https://github.com/rspamd/rspamd/blob/545e090c81ce22bbb7edb6d3621c348bd994449c/src/libserver/composites.c#L222
`~` is removing Symbol only.

**Comment by vstakhov** [comment]
Fixed, thanks!
