### ISSUE TITLE
Request for clarification regarding the documentation related to the upgrade to version 2.0.

### ISSUE THREAD

**Issue by gauthierc** [rspamd/rspamd.com#417]
Hello,
In the documentation on page https://rspamd.com/doc/migration.html#migration-to-rspamd-20 it says:

> ip_score module has been replaced by reputation module. The existing rules should be automatically converted to reputation rules. The name of symbol has also been changed to two symbols: SENDER_REP_SPAM and SENDER_REP_HAM. The scores of IP_SCORE should be automatically applied to new symbols. The data collected from ip_score plugin will be LOST unevitably. The main reason behind it was the significant flaw of the old plugin that caused reputation never expire.

What happens when you update a single node in a rspamd cluster that uses a single Redis database? 
Should all cluster nodes be updated at the same time?

Thanks!

**Comment by vstakhov** [comment]
It doesn't matter: Rspamd 2.0 uses different keys.

**Comment by gauthierc** [comment]
Thank you, I will soon plan my update.
