### ISSUE TITLE
RBL module config shows wrong default value for `default_unknown`

### ISSUE THREAD

**Issue by denschub** [rspamd/rspamd.com#515]
On https://rspamd.com/doc/modules/rbl.html, the documentation states

> default_unknown: if set to false, do not yield a result unless the response received from the RBL is defined in its related returncodes {} subsection, else return the default symbol for the RBL (**false by default**).

However, this contradicts the current default config:

https://github.com/rspamd/rspamd/blob/333b82b2bf8b014b55268881897251d55c3cdca0/conf/modules.d/rbl.conf#L18

**Comment by fatalbanana** [comment]
There are true-defaults and default-configuration-defaults and they might not be the same, maybe it'd be best to highlight both in such cases...

Defaults about things to check (like `emails`, `helo` etc) should be removed and `checks` setting should be documented.

**Comment by vstakhov** [comment]
I have started this change in the meantime. Rbl module documentation is awful tbh...
