### ISSUE TITLE
Rspamd install not possible after updates

### ISSUE THREAD

**Issue by areimund** [rspamd/rspamd.com#578]
during update of Ubuntu i lost the rspamd.
if i now start with apt-get install rspamd follow failure shown
Die folgenden Pakete haben unerfüllte Abhängigkeiten:
 rspamd : Hängt ab von: libc++1-13 (>= 1:13.0.1~++20220120110844+75e33f71c2da) ist aber nicht installierbar
          Hängt ab von: libc++abi1-13 (>= 1:13.0.1~++20220120110844+75e33f71c2da) ist aber nicht installierbar
          Hängt ab von: libunwind-13 (>= 1:13.0.1~++20220120110844+75e33f71c2da) ist aber nicht installierbar

First install of rspamd worked without problems.

**Comment by vstakhov** [comment]
Duplicate of https://github.com/rspamd/rspamd/issues/4287
