### ISSUE TITLE
Website not accessible from my IP address

### ISSUE THREAD

**Issue by Player701** [rspamd/rspamd.com#790]
Hello. Terribly sorry if this is the wrong place to report such problems, but I simply have no idea where else to go. I've already sent a message to the `support` email regarding this issue, but so far there has been no response.

Since about 2-3 weeks ago, the Rspamd website has become inaccessible from my VPS - the connection simply times out:

```
$ curl -v https://rspamd.com
* Trying 135.181.136.158:443...
* connect to 135.181.136.158 port 443 failed: Connection timed out
* Failed to connect to rspamd.com port 443 after 129826 ms: Connection timed out
* Closing connection 0
curl: (28) Failed to connect to rspamd.com port 443 after 129826 ms: Connection timed out
```

The worst thing is that I can no longer access the APT repository and thus upgrade automatically, which is really inconvenient:

```
$ sudo apt update
...
W: Failed to fetch https://rspamd.com/apt-stable/dists/jammy/InRelease  Could not connect to rspamd.com:443 (135.181.136.158),
```

I'm not experiencing any issues accessing other websites or services, which leads me to believe that my IP has been blocked by rspamd.com. I have exactly zero idea as to why this could have happened, except perhaps by mistake. I'm fairly certain that my server hasn't been generating any malicious traffic, so I'd like to contact the admins to have this resolved.

If possible, could you please provide me with contact information so that I do not have to disclose my IP address publicly?

Thank you very much.

**Comment by Player701** [comment]
Despite the lack of any feedback, it appears the issue is gone now. Thank you very much! Closing.

**Comment by vstakhov** [comment]
Just in case: there is no blocking of site from our side for any IP.
